### ISSUE TITLE
How to use a second disk

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/rTS_Wiki#11]
We need an article explaining proper usage of multiple disks. People get a second disk, or an external and copy-paste stupid things 

This could include directions on Library functions in Steam

**Comment by SealsRock12** [comment]
It should be under Disks if we do it

**Comment by Willzy12h** [comment]
# How to use multiple disks in Windows

**Always** install your applications onto your **primary drive**. You can not install applications onto your second drive because you think it means you won't have to reinstall them next time you clean install windows. Everything will have to be installed again, but you can install the application data and games onto the secondary drive.

When you install applications, the data and files get stored in multiple locations and the registry (which you should never mess around with). Because of this, this is why every application has to be re-installed when you get a new operating system installed.

*It is **recommended** to install all your programs onto your **"C:\\"** Drive (Your primary drive) and then, where appropriate, change the install path for games and roaming data onto your secondary drives.*

# Storing Data on my other drive(s)
Once you install your software on your **primary drive**, you often can point the data path to other drives. You can do this with your downloads from your internet browser, videos and pictures and any games you download, for example.

You can change your default location for your download folder by **right-clicking the download folder**, selecting **properties > Location >**, then type in or "find target" of your other drive where you want it to reside. 


You can casually store any other data, like **documents, pictures, and videos, on the external drive without any issues**, create a new folder and keep them as you usually would. 

For things like Games, often, you can change the install path to be on your external drive. When you install games using a platform like **Steam, Battle.net, EA/Origin, or Epic Games**, you can often tell them where to install the games or even create a new game library so games will install there by default.

 
**See links below on how to change game installs/library paths.**
*You can also copy and paste the data to your other drive if you have it installed, and when the install checks the data, it will see everything is there, and you won't have to re-download everything.*

**Steam** - [Steam Support :: Moving a Steam Installation and Games (steampowered.com)](https://help.steampowered.com/en/faqs/view/4BD4-4528-6B2E-8327)
**Battle.net** - [How Do I Install Blizzard Games on a Different Hard Drive? - Blizzard Support (battle.net)](https://us.battle.net/support/en/article/151376#:~:text=Open%20the%20Blizzard%20Battle.net,Click%20%22Start%20Install%22) 
**Origin** - Copy your game install folder to your other drive, then reinstall, pointing to the new location
**Epic Games** - Copy your game install folder to your other drive, then reinstall, pointing to the new location


***If you are unsure of what you are doing, make sure you take a backup of your data.***

**Comment by TheKrol** [comment]
Updated the file, #Raid still needs to be filled in
